version: "3.7"
   
services:
  nginx:
    container_name: nginx_proxy
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - api_movie_hub

  db_movie_hub:
    image: postgres:12-alpine
    container_name: db_movie_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - dev.env

  api_movie_hub:
    build: .
    restart: always
    container_name: api_movie_hub
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:5000 && celery -A core worker -l info"
    volumes:
      - ./api:/app/
      - static_volume:/app/static
    env_file:
      - dev.env

    depends_on:
      - db_movie_hub
      - broker

  broker:
    image: rabbitmq:3-management-alpine
    container_name: broker_rabbitmq
    hostname: broker
    env_file:
      - dev.env
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    image: mher/flower
    container_name: flower
    env_file:
      - dev.env
    ports:
      - "5555:5555"
    depends_on:
      - broker

volumes:
  postgres_data:
  static_volume: