# Generated by Django 4.1 on 2022-08-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_excerpt_books_author_books_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
