# Generated by Django 3.2.15 on 2022-08-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
