# Generated by Django 3.2.15 on 2022-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extenduser_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
